version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/mysql_db_files:/var/lib/mysql

  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'auth'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./postgres/postgres_db_files:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: 'user'
      PMA_PASSWORD: 'password'
      PHP_UPLOAD_MAX_FILESIZE: '100MB'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  mysql_db_files:
  postgres_db_files:
